---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: SERVICE-NAME
  namespace: NAMESPACE
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: SERVICE-NAME
        version: VERSION
    spec:
      containers:
      - name: SERVICE-NAME
        image: CONTAINER-IMAGE
        env:
        - name: DT_CUSTOM_PROP
          value: SERVICE_TYPE=FRONTEND
        ports:
        - containerPort: CONTAINER-PORT
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: CONTAINER-PORT
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: CONTAINER-PORT
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE-NAME
  labels:
    app: SERVICE-NAME
  namespace: NAMESPACE
spec:
  ports:
  - name: http
    port: EXTERNAL-PORT
    targetPort: CONTAINER-PORT
  selector:
    app: SERVICE-NAME
  type: LoadBalancer